export const peixesIniciais = [
  { id: 1, imagem: '/peixe.png', lado: 'esquerda', offset: 30, profundidade: 0, tamanho: 100, espelhado: true, usuario: { id: 1, username: 'mar_azul', nome: 'Marina Azul', foto: 'https://randomuser.me/api/portraits/women/1.jpg', cadastradoEm: '2025-01-12' } },
  { id: 2, imagem: '/peixe.png', lado: 'direita', offset: 25, profundidade: 140, tamanho: 90, espelhado: false, usuario: { id: 2, username: 'nado_livre', nome: 'Nando Lima', foto: 'https://randomuser.me/api/portraits/men/2.jpg', cadastradoEm: '2025-02-03' } },
  { id: 3, imagem: '/peixe.png', lado: 'esquerda', offset: 35, profundidade: 210, tamanho: 110, espelhado: true, usuario: { id: 3, username: 'coral_vivo', nome: 'Cora Alves', foto: 'https://randomuser.me/api/portraits/women/3.jpg', cadastradoEm: '2025-02-18' } },
  { id: 4, imagem: '/peixe.png', lado: 'direita', offset: 10, profundidade: 290, tamanho: 82.5, espelhado: true, usuario: { id: 4, username: 'onda_mansa', nome: 'Otávio Mendes', foto: 'https://randomuser.me/api/portraits/men/4.jpg', cadastradoEm: '2025-03-09' } },
  { id: 5, imagem: '/peixe.png', lado: 'esquerda', offset: 20, profundidade: 375, tamanho: 105, espelhado: false, usuario: { id: 5, username: 'abissal', nome: 'Bia Salles', foto: 'https://randomuser.me/api/portraits/women/5.jpg', cadastradoEm: '2025-03-21' } },
  { id: 6, imagem: '/peixe.png', lado: 'direita', offset: 30, profundidade: 450, tamanho: 95, espelhado: false, usuario: { id: 6, username: 'cardume', nome: 'Caio Duarte', foto: 'https://randomuser.me/api/portraits/men/6.jpg', cadastradoEm: '2025-04-04' } },
  { id: 7, imagem: '/peixe.png', lado: 'esquerda', offset: 8, profundidade: 550, tamanho: 115, espelhado: true, usuario: { id: 7, username: 'marinheira', nome: 'Marina Reis', foto: 'https://randomuser.me/api/portraits/women/7.jpg', cadastradoEm: '2025-04-27' } },
  { id: 8, imagem: '/peixe.png', lado: 'direita', offset: 18, profundidade: 650, tamanho: 87.5, espelhado: false, usuario: { id: 8, username: 'mergulho', nome: 'Murilo Costa', foto: 'https://randomuser.me/api/portraits/men/8.jpg', cadastradoEm: '2025-05-11' } },
  { id: 9, imagem: '/peixe.png', lado: 'esquerda', offset: 28, profundidade: 750, tamanho: 107.5, espelhado: true, usuario: { id: 9, username: 'baleia_azul', nome: 'Bruna Azevedo', foto: 'https://randomuser.me/api/portraits/women/9.jpg', cadastradoEm: '2025-05-28' } },
  { id: 10, imagem: '/peixe.png', lado: 'direita', offset: 12, profundidade: 875, tamanho: 97.5, espelhado: false, usuario: { id: 10, username: 'correnteza', nome: 'Clara Teixeira', foto: 'https://randomuser.me/api/portraits/women/10.jpg', cadastradoEm: '2025-06-16' } }
];